# Generated by Django 4.1.1 on 2022-09-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Obligāti', max_length=255, unique=True, verbose_name='Produkta nosaukums')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Produkta veids',
                'verbose_name_plural': 'Produkta veidi',
            },
        ),
    ]
