# Generated by Django 4.1.1 on 2022-09-19 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0002_producttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ir aktīvs'),
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Obligāti', max_length=255, verbose_name='Nosaukums')),
                ('Product_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='majaslapa.producttype')),
            ],
            options={
                'verbose_name': 'Produkta specifikācija',
                'verbose_name_plural': 'Produkta specifikācijas',
            },
        ),
    ]
