# Generated by Django 4.1.1 on 2022-09-19 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0003_alter_producttype_is_active_productspecification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='nepieciešams', max_length=255, verbose_name='Nosaukums')),
                ('desciption', models.TextField(blank=True, help_text='nav nepieciešams', verbose_name='Apraksts')),
                ('slug', models.SlugField(max_length=255)),
                ('regular_price', models.DecimalField(decimal_places=2, error_messages={'name': {'max_lenght': 'Cenai jābūt no 0 līdz 9999,99!'}}, help_text='Maksimums 9999.99', max_digits=6, verbose_name='Parastā cena')),
                ('discount_price', models.DecimalField(decimal_places=2, error_messages={'name': {'max_lenght': 'Cenai jābūt no 0 līdz 9999,99!'}}, help_text='Maksimalais ir 9999.99', max_digits=6, verbose_name='Atlaides cena')),
                ('is_active', models.BooleanField(default=True, help_text='Mainīt produkta redzamību', verbose_name='Produkta redzamība')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Izveidots plkst')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Atjaunināts plkst')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='majaslapa.category')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='majaslapa.producttype')),
            ],
            options={
                'verbose_name': 'Prece',
                'verbose_name_plural': 'Preces',
                'ordering': ('-created_at',),
            },
        ),
    ]
