# Generated by Django 4.1.1 on 2022-09-19 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecificationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Produkta specifikācijas vērtība (maksimums 255 vārdi)', max_length=255, verbose_name='Value')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='majaslapa.product')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='majaslapa.productspecification')),
            ],
            options={
                'verbose_name': 'Produkta specifikacijas vērtība',
                'verbose_name_plural': 'Produkta specifikacijas vērtības',
            },
        ),
    ]
