# Generated by Django 4.1.1 on 2022-09-19 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0005_productspecificationvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/default.png', help_text='Augšupielādējiet produkta attēlu', upload_to='images/', verbose_name='Attēls')),
                ('alt_text', models.CharField(blank=True, help_text='Lūdzu pievienojiet alternatīvu tekstu', max_length=255, null=True, verbose_name='Alternatīva teksts')),
                ('is_feature', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Produkta_attēls', to='majaslapa.product')),
            ],
            options={
                'verbose_name': 'Produkta attēls',
                'verbose_name_plural': 'Produkta attēli',
            },
        ),
    ]
