# Generated by Django 4.1.1 on 2022-09-22 16:08

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0006_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ir aktīvs'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='majaslapa.category', verbose_name='Līdzīgie produkti'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='majaslapa.category', verbose_name='Kategorija'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='majaslapa.producttype', verbose_name='Produkta Veids'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='tīmekļa adreses identifikācija'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_feature',
            field=models.BooleanField(default=False, verbose_name='Galvenā bilde'),
        ),
        migrations.AlterField(
            model_name='productspecificationvalue',
            name='value',
            field=models.CharField(help_text='Produkta specifikācijas vērtība (maksimums 255 vārdi)', max_length=255, verbose_name='Vērtība'),
        ),
    ]
