# Generated by Django 4.1.1 on 2022-09-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majaslapa', '0007_alter_category_is_active_alter_category_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='images_category/default.png', help_text='Augšupielādējiet produkta attēlu', upload_to='images_category/', verbose_name='Attēls priekš kategorijas'),
        ),
    ]
